"""empty message

Revision ID: 1f8bbd3bec90
Revises: cb04edf3878e
Create Date: 2021-04-16 14:39:04.053384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8bbd3bec90'
down_revision = 'cb04edf3878e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UserInfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('pwd', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.Enum('男', '女'), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserInfo')
    op.drop_table('Department')
    # ### end Alembic commands ###
