"""empty message

Revision ID: cb04edf3878e
Revises: 
Create Date: 2021-04-15 10:25:05.480016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb04edf3878e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EnergyConcentrator',
    sa.Column('cont_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cont_name', sa.String(length=40), nullable=False),
    sa.Column('cont_place', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('cont_id')
    )
    op.create_table('EnergyMonitoringPoint',
    sa.Column('emp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_name', sa.String(length=40), nullable=False),
    sa.Column('emp_place', sa.String(length=50), nullable=False),
    sa.Column('emp_concentrator_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('emp_id')
    )
    op.create_table('EnergyRecord',
    sa.Column('energy_record_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('energy_rec_time', sa.String(length=80), nullable=True),
    sa.Column('energy_voltage_a', sa.Float(), nullable=True),
    sa.Column('energy_voltage_b', sa.Float(), nullable=True),
    sa.Column('energy_tap', sa.Integer(), nullable=True),
    sa.Column('energy_concentrator', sa.Integer(), nullable=True),
    sa.Column('energy_monitoring_point', sa.Integer(), nullable=True),
    sa.Column('energy_type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('energy_record_id')
    )
    op.create_table('EnergyType',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('energy_name', sa.String(length=10), nullable=True),
    sa.Column('energy_type', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EnergyType')
    op.drop_table('EnergyRecord')
    op.drop_table('EnergyMonitoringPoint')
    op.drop_table('EnergyConcentrator')
    # ### end Alembic commands ###
